[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'
hook_post_update = '''
let g:dein#plugin.build = 'git submodule update --init'
'''

hook_add = '''
let g:deoplete#sources#jedi#python_path = '/Users/tsuchidayuuki/.pyenv/shims/python3'
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

