[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft = 'cs'

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = 'cs'
hook_add = '''
let g:OmniSharp_host = "http://localhost:2000"

let g:OmniSharp_selector_ui = 'ctrlp' 

nnoremap [omnisharp]    <Nop>
nmap <Space>os	[omnisharp]
au Filetype cs noremap <silent>[omnisharp]gd		:OmniSharpGotoDefinition<CR>
au Filetype cs noremap <silent>[omnisharp]fu		:OmniSharpFindUsages<CR>
au Filetype cs noremap <silent>[omnisharp]ca		:OmniSharpGetCodeActions<CR>
au Filetype cs noremap <silent>[omnisharp]rename	:OmniSharpRename<CR>
au Filetype cs noremap <silent>[omnisharp]reload	:OmniSharpReloadSolution<CR>
au Filetype cs noremap <silent>[omnisharp]format	:OmniSharpCodeFormat<CR>
'''

hook_post_update = '''
if dein#util#_is_mac()
    let cmd = 'cd server && xbuild'
elif dein#util#_is_windows()
    let cmd = 'cd server && msbuild'
else
    let cmd = 'cd server && xbuild'
endif
let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Robzz/deoplete-omnisharp'
on_ft = 'cs'

[[plugins]]
repo = 'OrangeT/vim-csharp'
