[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup=1
"let g:indent_guides_color_change_percent=30
"let g:indent_guides_guide_size=1
"let g:indent_guides_start_level=2
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
'''


[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_post_source = '''
colorscheme solarized
'''
